from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)


def _build_styles():
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="SectionHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=14,
            textColor=colors.white,
            backColor=colors.HexColor("#1A7A50"),
            leftIndent=0,
            rightIndent=0,
            spaceBefore=12,
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="BodyTextSmall",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=11,
        )
    )

    styles.add(
        ParagraphStyle(
            name="BodyTextItalic",
            parent=styles["BodyTextSmall"],
            fontName="Helvetica-Oblique",
        )
    )

    styles.add(
        ParagraphStyle(
            name="BodyTextBold",
            parent=styles["BodyTextSmall"],
            fontName="Helvetica-Bold",
        )
    )

    return styles


def _nice_param_name(key: str) -> str:
    return key.replace("_", " ").title()


def _draw_header(canvas, doc, patient_data):
    width, height = A4
    margin = 1.8 * cm

    canvas.saveState()

    header_height = 3.5 * cm
    header_y = height - margin - header_height

    dark_green = colors.HexColor("#0D5C3A")
    light_green = colors.HexColor("#E8F5EE")

    canvas.setFillColor(dark_green)
    canvas.rect(
        0,
        header_y,
        width,
        header_height,
        stroke=0,
        fill=1,
    )

    canvas.setFillColor(light_green)
    bar_height = 0.8 * cm
    canvas.rect(
        0,
        header_y - bar_height,
        width,
        bar_height,
        stroke=0,
        fill=1,
    )

    canvas.setFillColor(colors.white)

    canvas.setFont("Helvetica-Bold", 18)
    canvas.drawString(margin, header_y + header_height - 1.1 * cm, "NutriPattern AI")

    canvas.setFont("Helvetica", 10)
    canvas.drawString(
        margin,
        header_y + header_height - 1.1 * cm - 12,
        "Personalized Health & Diet Report",
    )

    right_x = width - margin
    text_y = header_y + header_height - 1.0 * cm
    canvas.setFont("Helvetica", 9)

    def draw_right(label, value, offset):
        label_text = f"{label}: {value}"
        text_width = canvas.stringWidth(label_text, "Helvetica", 9)
        canvas.drawString(right_x - text_width, offset, label_text)

    name = patient_data.get("name", "N/A")
    age = patient_data.get("age", "N/A")
    gender = patient_data.get("gender", "N/A")
    report_date = patient_data.get("report_date", "N/A")

    draw_right("Name", name, text_y)
    draw_right("Age", age, text_y - 12)
    draw_right("Gender", gender, text_y - 24)
    draw_right("Report Date", report_date, text_y - 36)

    canvas.setFillColor(colors.HexColor("#0D5C3A"))
    canvas.setFont("Helvetica-Bold", 10)
    score = patient_data.get("wellness_score", 0) or 0
    patient_id = patient_data.get("username") or patient_data.get("name", "N/A")
    label_text = f"Patient ID: {patient_id}    Wellness Score: {score}/100"
    text_width = canvas.stringWidth(label_text, "Helvetica-Bold", 10)
    canvas.drawString((width - text_width) / 2.0, header_y - bar_height + 0.25 * cm, label_text)

    canvas.restoreState()


def _draw_footer(canvas, doc):
    width, _ = A4
    margin = 1.8 * cm

    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#1A7A50"))
    canvas.setLineWidth(0.6)
    footer_y = margin - 0.6 * cm
    canvas.line(margin, footer_y, width - margin, footer_y)

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#444444"))
    timestamp = datetime.now().strftime("%d %b %Y %H:%M")
    text = (
        "Generated by NutriPattern AI | CMR College of Engineering & Technology, Hyderabad | "
        f"{timestamp} | This report is AI-generated. Please consult your physician before making dietary changes."
    )
    text_width = canvas.stringWidth(text, "Helvetica", 7)
    canvas.drawString((width - text_width) / 2.0, footer_y - 8, text)

    canvas.restoreState()


def generate_patient_report(patient_data: dict) -> BytesIO:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=1.8 * cm,
        rightMargin=1.8 * cm,
        topMargin=4.5 * cm,
        bottomMargin=2.4 * cm,
    )

    styles = _build_styles()
    Story = []

    parameters = patient_data.get("parameters") or {}
    diet_chart = patient_data.get("diet_chart") or []
    wellness_score = patient_data.get("wellness_score", 0) or 0
    wellness_tips = patient_data.get("wellness_tips") or []
    doctor_notes = (patient_data.get("doctor_notes") or "") or ""
    conditions = patient_data.get("conditions") or []
    activity_summary = patient_data.get("activity_summary") or {}

    section_elements = []

    heading = Paragraph("HEALTH PARAMETERS", styles["SectionHeader"])
    section_block = [heading, Spacer(1, 6)]

    if not parameters:
        section_block.append(
            Paragraph(
                "No health data available yet.",
                styles["BodyTextSmall"],
            )
        )
    else:
        table_data = [
            [
                Paragraph("<b>Parameter Name</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Current Value</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Previous Value</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Change</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Status</b>", styles["BodyTextSmall"]),
            ]
        ]

        for idx, (key, data) in enumerate(sorted(parameters.items(), key=lambda x: x[0])):
            if key.endswith("_unit"):
                continue

            latest = data.get("value", "")
            previous = data.get("previous")
            change_flag = (data.get("change") or "").lower()
            status_text = (data.get("status") or "Normal").title()

            if isinstance(latest, float):
                latest_str = f"{latest:.2f}"
            else:
                latest_str = str(latest)

            if previous is None:
                previous_str = "—"
            else:
                if isinstance(previous, float):
                    previous_str = f"{previous:.2f}"
                else:
                    previous_str = str(previous)

            if previous is None:
                change_str = "→ Stable"
                change_color = colors.HexColor("#7F8C8D")
            else:
                try:
                    diff = float(latest) - float(previous)
                except Exception:
                    diff = 0.0

                if change_flag == "improved":
                    change_str = f"↑ {diff:+.1f}"
                    change_color = colors.HexColor("#1A7A50")
                elif change_flag == "worse":
                    change_str = f"↓ {diff:+.1f}"
                    change_color = colors.HexColor("#C0392B")
                else:
                    change_str = "→ Stable"
                    change_color = colors.HexColor("#7F8C8D")

            if status_text.lower() == "normal":
                status_color = colors.HexColor("#1A7A50")
            elif status_text.lower() == "low":
                status_color = colors.HexColor("#E67E22")
            elif status_text.lower() == "high":
                status_color = colors.HexColor("#C0392B")
            else:
                status_color = colors.black

            table_data.append(
                [
                    Paragraph(_nice_param_name(key), styles["BodyTextSmall"]),
                    Paragraph(latest_str, styles["BodyTextSmall"]),
                    Paragraph(previous_str, styles["BodyTextSmall"]),
                    Paragraph(f'<font color="{change_color.hexval()}">{change_str}</font>', styles["BodyTextSmall"]),
                    Paragraph(f'<font color="{status_color.hexval()}">{status_text}</font>', styles["BodyTextSmall"]),
                ]
            )

        table = Table(table_data, colWidths=[5 * cm, 2.5 * cm, 2.5 * cm, 3 * cm, 2.5 * cm])
        grid_color = colors.HexColor("#C8E6D4")
        light_row = colors.HexColor("#E8F5EE")

        style_commands = [
            ("GRID", (0, 0), (-1, -1), 0.4, grid_color),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A7A50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (1, 1), (-2, -1), "CENTER"),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

        row_index = 1
        for i in range(len(parameters)):
            if i % 2 == 1:
                style_commands.append(("BACKGROUND", (0, row_index + i), (-1, row_index + i), light_row))

        table.setStyle(TableStyle(style_commands))
        section_block.append(table)

    section_elements.append(KeepTogether(section_block))

    if conditions:
        heading = Paragraph("DETECTED CONDITIONS", styles["SectionHeader"])
        block = [heading, Spacer(1, 6)]

        box_bg = colors.HexColor("#FFF8E7")
        border_color = colors.HexColor("#E67E22")

        bullet_rows = []
        for cond in conditions:
            bullet_rows.append(
                [
                    Paragraph(
                        f"• {cond}",
                        styles["BodyTextSmall"],
                    )
                ]
            )

        if bullet_rows:
            tbl = Table(bullet_rows, colWidths=[doc.width])
            tbl.setStyle(
                TableStyle(
                    [
                        ("BOX", (0, 0), (-1, -1), 0.6, border_color),
                        ("BACKGROUND", (0, 0), (-1, -1), box_bg),
                        ("LEFTPADDING", (0, 0), (-1, -1), 8),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            block.append(tbl)

        section_elements.append(KeepTogether(block))

    heading = Paragraph("PERSONALIZED DIET PLAN", styles["SectionHeader"])
    block = [heading, Spacer(1, 6)]

    if not diet_chart:
        block.append(
            Paragraph(
                "No diet plan generated yet.",
                styles["BodyTextSmall"],
            )
        )
    else:
        rows = [
            [
                Paragraph("<b>Meal</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Food Items</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Calories</b>", styles["BodyTextSmall"]),
                Paragraph("<b>Reason</b>", styles["BodyTextSmall"]),
            ]
        ]
        for idx, meal in enumerate(diet_chart):
            meal_name = meal.get("meal", "")
            items = meal.get("items", "")
            calories = meal.get("calories", "")
            reason = meal.get("reason", "")

            if isinstance(items, list):
                items_text = ", ".join(items)
            else:
                items_text = str(items)

            rows.append(
                [
                    Paragraph(f'<font color="#1A7A50"><b>{meal_name}</b></font>', styles["BodyTextSmall"]),
                    Paragraph(items_text, styles["BodyTextSmall"]),
                    Paragraph(str(calories), styles["BodyTextSmall"]),
                    Paragraph(f'<font color="#666666"><i>{reason}</i></font>', styles["BodyTextSmall"]),
                ]
            )

        diet_table = Table(
            rows,
            colWidths=[3 * cm, 6 * cm, 2.5 * cm, doc.width - (3 * cm + 6 * cm + 2.5 * cm)],
        )
        style_cmds = [
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C8E6D4")),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A7A50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]

        for i in range(1, len(rows)):
            if (i - 1) % 2 == 1:
                style_cmds.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#E8F5EE")))

        diet_table.setStyle(TableStyle(style_cmds))
        block.append(diet_table)

    section_elements.append(KeepTogether(block))

    heading = Paragraph("WELLNESS SUMMARY", styles["SectionHeader"])
    block = [heading, Spacer(1, 6)]

    score_color = (
        "#1A7A50"
        if wellness_score >= 80
        else ("#E67E22" if wellness_score >= 60 else "#C0392B")
    )

    if wellness_score >= 80:
        interpretation = "Excellent — Keep it up!"
    elif wellness_score >= 60:
        interpretation = "Good — Some areas need attention"
    else:
        interpretation = "Needs Improvement — Consult your doctor"

    total_steps = activity_summary.get("total_steps", 0) or 0
    total_calories = activity_summary.get("total_calories", 0) or 0
    days_logged = activity_summary.get("days_logged", 0) or 0

    left_para = Paragraph(
        f'<para align="center"><font size="20" color="{score_color}"><b>{wellness_score}</b></font>'
        '<font size="11"> / 100</font><br/><font size="9">'
        f"{interpretation}"
        "</font></para>",
        styles["BodyTextSmall"],
    )

    right_para = Paragraph(
        "<para align='left'>"
        f"<b>Activity Summary</b><br/>"
        f"Steps Logged: {int(total_steps)}<br/>"
        f"Calories Burned: {int(total_calories)}<br/>"
        f"Days Logged: {int(days_logged)}</para>",
        styles["BodyTextSmall"],
    )

    wellness_table = Table(
        [[left_para, right_para]],
        colWidths=[doc.width * 0.45, doc.width * 0.55],
    )
    wellness_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 0.4, colors.HexColor("#C8E6D4")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F6F8FA")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    block.append(wellness_table)
    section_elements.append(KeepTogether(block))

    heading = Paragraph("WELLNESS TIPS", styles["SectionHeader"])
    block = [heading, Spacer(1, 6)]

    if not wellness_tips:
        block.append(
            Paragraph(
                "No wellness tips available.",
                styles["BodyTextSmall"],
            )
        )
    else:
        tips = wellness_tips[:6]
        rows = []
        for idx, tip in enumerate(tips, start=1):
            rows.append(
                [
                    Paragraph(
                        f"{idx}. {tip}",
                        styles["BodyTextSmall"],
                    )
                ]
            )

        tips_table = Table(rows, colWidths=[doc.width])
        tips_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#E8F5EE")),
                    ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#E8F5EE")]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("BOX", (0, 0), (-1, -1), 0.4, colors.HexColor("#C8E6D4")),
                ]
            )
        )
        block.append(tips_table)

    section_elements.append(KeepTogether(block))

    if doctor_notes and str(doctor_notes).strip():
        heading = Paragraph("CLINICIAN NOTES", styles["SectionHeader"])
        block = [heading, Spacer(1, 6)]

        notes_table = Table(
            [
                [
                    Paragraph(
                        str(doctor_notes),
                        styles["BodyTextItalic"],
                    )
                ]
            ],
            colWidths=[doc.width],
        )
        notes_table.setStyle(
            TableStyle(
                [
                    ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#E67E22")),
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFF8E7")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        block.append(notes_table)
        section_elements.append(KeepTogether(block))

    for sec in section_elements:
        Story.append(sec)
        Story.append(Spacer(1, 12))

    def _on_page(canvas, doc_):
        _draw_header(canvas, doc_, patient_data)
        _draw_footer(canvas, doc_)

    doc.build(Story, onFirstPage=_on_page, onLaterPages=_on_page)

    buffer.seek(0)
    return buffer


if __name__ == "__main__":
    sample_patient_data = {
        "name": "John Doe",
        "age": 42,
        "gender": "Male",
        "report_date": datetime.now().strftime("%d %b %Y"),
        "parameters": {
            "hemoglobin_hb": {
                "value": 13.5,
                "previous": 12.8,
                "status": "Normal",
                "change": "improved",
            },
            "fasting_blood_sugar_fbs": {
                "value": 110.0,
                "previous": 95.0,
                "status": "High",
                "change": "worse",
            },
            "total_cholesterol": {
                "value": 190.0,
                "previous": 210.0,
                "status": "Normal",
                "change": "improved",
            },
        },
        "diet_chart": [
            {
                "meal": "Breakfast",
                "items": "Oatmeal, Skimmed Milk, Almonds",
                "calories": 320,
                "reason": "High fiber breakfast to support stable blood sugar and sustained energy.",
            },
            {
                "meal": "Lunch",
                "items": "Brown Rice, Grilled Chicken, Mixed Vegetables",
                "calories": 540,
                "reason": "Balanced meal with lean protein and complex carbohydrates.",
            },
        ],
        "wellness_score": 78,
        "wellness_tips": [
            "Aim for at least 30 minutes of brisk walking most days.",
            "Include leafy green vegetables in at least one meal daily.",
            "Limit sugary beverages and choose water instead.",
            "Maintain consistent sleep and wake times.",
            "Schedule regular follow-ups with your healthcare provider.",
            "Practice deep breathing exercises for 5 minutes daily.",
        ],
        "doctor_notes": "Overall parameters are improving. Continue current diet and activity plan. Recheck in 3 months.",
        "conditions": [
            "High Blood Sugar (Fasting)",
            "Borderline High Cholesterol",
        ],
        "activity_summary": {
            "total_steps": 42000,
            "total_calories": 6200,
            "days_logged": 7,
        },
        "username": "JD1234",
    }

    pdf_buffer = generate_patient_report(sample_patient_data)
    with open("NutriPattern_Sample_Report.pdf", "wb") as f:
        f.write(pdf_buffer.getvalue())

