#!/usr/bin/env python3
"""
Environment Setup Script for NutriPattern AI
This script helps you create a secure .env file with your credentials.
"""

import os

def create_env_file():
    """Create .env file for NutriPattern AI"""
    
    print("🔐 ENVIRONMENT SETUP")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("❌ Setup cancelled.")
            return
    
    print("\n📝 Setting up environment variables...")
    
    # Get credentials
    secret_key = input("\n🔐 Flask Secret Key (press Enter for random): ").strip()
    if not secret_key:
        import secrets
        secret_key = secrets.token_hex(32)
        print(f"✅ Generated random secret key")
    
    openrouter_key = input("🤖 OpenRouter API Key (optional, for chatbot features): ").strip()
    
    # Create .env content
    env_content = f"""# Environment Variables for NutriPattern AI
# Generated by setup script

# Flask Configuration
SECRET_KEY={secret_key}
DATABASE_URL=sqlite:///healthapp.db

# OpenRouter API (for AI chatbot features)
OPENROUTER_API_KEY={openrouter_key}
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        print("🔒 Your credentials are secure and won't be committed to Git")
        print("\n📋 Next steps:")
        print("1. Run: ./run.sh (or python app.py)")
        print("2. Open http://127.0.0.1:5000 in your browser")
            
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")

if __name__ == "__main__":
    create_env_file()
